# gcloud compute firewall-rules create test --allow tcp:NODEPORT
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  namespace: factor4
spec:
  type: NodePort
  selector:
    app: nginx
    type: nodePort
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeport
  namespace: factor4
  labels:
    app: nginx
    type: nodePort
spec:
  containers:
  - name: nginx
    image: nginx:alpine
