---
apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
  namespace: factor4
spec:
  type: ClusterIP
  selector:
    app: nginx
    type: clusterIP
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-clusterip
  namespace: factor4
  labels:
    app: nginx
    type: clusterIP
spec:
  containers:
  - name: nginx
    image: nginx:alpine
