---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: factor4
spec:
  type: LoadBalancer
  selector:
    app: nginx
    type: lb
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-lb
  namespace: factor4
  labels:
    app: nginx
    type: lb
spec:
  containers:
  - name: nginx
    image: nginx:alpine
