---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: stateful-app
  namespace: factor10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stateful
  template:
    metadata:
      labels:
        app: stateful
    spec:
      containers:
      - name: stateful
        image: etiennecoutaud/statefull-app:0.1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: factor10
spec:
  type: ClusterIP
  selector:
    app: stateful
  ports:
  - protocol: TCP
    port: 8080